### ISSUE TITLE
fail to open pr after successful release

### ISSUE THREAD

**Issue by flynneva** [at-wat/bloom-release-action#15]
hi at-wat! first off - great action! this thing is awesome to use and was super easy to setup.
I am working on automating my first ROS release and am running into an issue.
I've already manually made the first PR for melodic for the udp_com package I am trying to release.

[here is a link to the action failing](https://github.com/continental/udp_com/runs/951039206?check_suite_focus=true#step:4:218)
this is the error:
```
==> Generating pull request to distro file located at 'https://raw.githubusercontent.com/ros/rosdistro/3edf3f9d5dca14dee800cf0645f3222447c0ef03/melodic/distribution.yaml'
Failed to open pull request: error - (25, 'Not a tty')
```

I dont really understand the error, and [everything works great if I comment out the open_pr line](https://github.com/continental/udp_com/actions/runs/195236732) from the release action.

Any ideas how to solve this issue?

**Comment by flynneva** [comment]
the only difference ive been able to find between your example action and my yml is that I am initiating it off of a non-default branch. I would think that this wouldnt matter...but maybe?

**Comment by at-wat** [comment]
The error message seems from https://github.com/ros-infrastructure/bloom/blob/1b9c46fcc4b15cfd958fc13ff0affa6635491a10/bloom/commands/release.py#L1133
I'll dig into it.

**Comment by at-wat** [comment]
As the error message is `Not a tty`, I suppose `bloom-release` tried to ask something interactive and failed.

**Comment by flynneva** [comment]
im going to try refreshing my token and see if that does the trick

**Comment by flynneva** [comment]
yeah that was it....thanks for the tip!

**Comment by qiayuanliao** [comment]
How can you solve this problem? I got the same error and try refreshing my token but still doesn't work.
[the link to falling action](https://github.com/rm-controls/rm_control/runs/3486838043)

**Comment by at-wat** [comment]
@qiayuanliao The error indicates that the token doesn't have enough permission to open a PR on rosdistro and the bloom command tried to ask login information but was not possible since it's not a tty.
Does the token have proper permission?

**Comment by qiayuanliao** [comment]
> @qiayuanliao The error indicates that the token doesn't have enough permission to open a PR on rosdistro and the bloom command tried to ask login information but was not possible since it's not a tty.
> Does the token have proper permission?

I tried open all premission, bu got the same erro .

**Comment by at-wat** [comment]
Hmm, on successful bloom-release action, the log should be like
https://github.com/at-wat/neonavigation/runs/3473186624?check_suite_focus=true#step:4:770

**Comment by qiayuanliao** [comment]
I tried deleting the token and add a new one but still got the same error, so strange.

**Comment by qiayuanliao** [comment]
I found that when I deleted the repo I forked from [rosdistro](https://github.com/qiayuanliao/rosdistro), I still got the same error.

**Comment by at-wat** [comment]
@qiayuanliao I added `debug_bloom` option which just pass `--debug` option to `bloom-release` command.
Could you try setting
```yaml
  debug_bloom: true
```
